# Ubuntu Server 20.04 LTS 64bit 操作系统下部署
version: "3"
services:
  client:
    # 前端项目dockerfile路径
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    # 镜像名
    image: client-image
    # 容器名
    container_name: client-container
    ports:
      - 8080:8080
    # 自定义网络 方便容器之间 通过[容器名]通信, [ip]会变的，不方便
    networks:
      - mysql_bridge
    # 依赖于后台服务 因为我们在前面定义的nginx中请求后台了
    depends_on:
      - server
    # 将项目的nginx卷映射到容器中
    volumes:
      - ./packages/client/nginx.conf:/etc/nginx/conf.d/default.conf

  server:
    # 前端项目dockerfile路径
    build: ./packages/server
    image: server-image
    container_name: server-container
    ports:
      - 3000:3000
    restart: on-failure
    networks:
      - mysql_bridge
    depends_on:
      - mysql

  mysql:
    restart: always
    image: daocloud.io/library/mysql:5.7
    container_name: mysql-db # 容器名
    ports:
      - 3306:3306
    networks:
      - mysql_bridge
    environment:
      MYSQL_ROOT_PASSWORD: jueduianquan996
      MYSQL_DATABASE: blowsysun
    volumes:
      - /usr/local/mysql/conf/mysql:/etc/mysql
      - /usr/local/mysql/data:/var/lib/mysql/

# 声明一下网桥  my-server。
# 重要：将所有服务都挂载在同一网桥即可通过容器名来互相通信了
# 如egg连接mysql和redis，可以通过容器名来互相通信
networks:
  mysql_bridge:
    driver: bridge
